### ISSUE TITLE
Update versioning on Triton

### ISSUE THREAD

**Issue by ruokolt** [AaltoRSE/speech2text#19]
The guideline for versioning on Triton uses currently a date-based approach:

YYYYMMDD

e.g.

20240113

This gives a quick overview of when the versions were added by just listing folders/files and `module load speech2text` automatically returns the latest version as it should.

However, this format doesn't support multiple version additions within the same day. Therefore, let's switch to another format with a year/month/day plus a running number, e.g.

20240113-01
20240113-02
20240525-01
20241010-01
20241010-02

and so forth or just

2024-01
2024-02

and so forth.

**Comment by hsnfirooz** [comment]
Thanks!
